import type { Metadata } from 'next'
import { Sometype_Mono } from 'next/font/google'
import React from 'react'
import './globals.css'
// components
import MainNav from '@/components/MainNav'
import PageTransition from '@/components/PageTransition'
import RectanglesTransition from '@/components/RectanglesTransition'

const sometypeMono = Sometype_Mono({
	variable: '--font-sometype-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang='en'>
			<body className={`${sometypeMono.variable} antialiased`}>
				<RectanglesTransition />
				<PageTransition>
					<div className='flex'>
						{/* main nav */}
						<div className='hidden 2xl:flex w-[285px] h-screen bg-secondary'>
							<MainNav />
						</div>
						<div className='w-full max-w-[1130px] px-[15px] mx-auto bg-pink-50/10'>
							<header>header</header>
							<div>{children}</div>
						</div>
					</div>
				</PageTransition>
			</body>
		</html>
	)
}

export default RootLayout
